apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-job
data:
  upgrade-job.yaml: |
    prodGraphQLAddr: http://dgraph-public:8080
    upgradeFromVersion: July2024
    upgradeToVersion: Netradyne
